name: pre-commit

on:
  push:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout [${{ github.repository }}]
      #  uses: actions/checkout@v4

      - uses: tschm/cradle/actions/pre-commit@v0.1.59
